delete from Wilaya where true;
insert into Wilaya (name_) values("Adrar");
insert into Wilaya (name_) values("Chlef");
insert into Wilaya (name_) values("Laghouat");
insert into Wilaya (name_) values("Oum El Bouaghi");
insert into Wilaya (name_) values("Batna");
insert into Wilaya (name_) values("Béjaïa");
insert into Wilaya (name_) values("Biskra");
insert into Wilaya (name_) values("Béchar");
insert into Wilaya (name_) values("Blida");
insert into Wilaya (name_) values("Bouira");
insert into Wilaya (name_) values("Tamanrasset");
insert into Wilaya (name_) values("Tébessa");
insert into Wilaya (name_) values("Tlemcen");
insert into Wilaya (name_) values("Tiaret");
insert into Wilaya (name_) values("Tizi Ouzou");
insert into Wilaya (name_) values("Alger");
insert into Wilaya (name_) values("Djelfa");
insert into Wilaya (name_) values("Jijel");
insert into Wilaya (name_) values("Sétif");
insert into Wilaya (name_) values("Saïda");
insert into Wilaya (name_) values("Skikda");
insert into Wilaya (name_) values("Sidi Bel Abess");
insert into Wilaya (name_) values("Annaba");
insert into Wilaya (name_) values("Guelma");
insert into Wilaya (name_) values("Constantine");
insert into Wilaya (name_) values("Médéa");
insert into Wilaya (name_) values("Mostaganem");
insert into Wilaya (name_) values("M'Sila");
insert into Wilaya (name_) values("Mascara");
insert into Wilaya (name_) values("Ouargla");
insert into Wilaya (name_) values("Oran");
insert into Wilaya (name_) values("Bayadh");
insert into Wilaya (name_) values("Illizi");
insert into Wilaya (name_) values("Bordj Bou Arreridj");
insert into Wilaya (name_) values("Boumerdès");
insert into Wilaya (name_) values("El Tarf");
insert into Wilaya (name_) values("Tindouf");
insert into Wilaya (name_) values("Tissemsilt");
insert into Wilaya (name_) values("El Oued");
insert into Wilaya (name_) values("Khenchela");
insert into Wilaya (name_) values("Souk Ahras");
insert into Wilaya (name_) values("Tipaza");
insert into Wilaya (name_) values("Mila");
insert into Wilaya (name_) values("Aïn Defla");
insert into Wilaya (name_) values("Naâma");
insert into Wilaya (name_) values("Aïn Témouchent");
insert into Wilaya (name_) values("Ghardïa");
insert into Wilaya (name_) values("Relizane");

SELECT * FROM Madinatic.Wilaya;